SpaceXUI/Models/CrewVM.cs
namespace SpaceXUI.Models
{
    public class CrewVM
    {
        public string? Name { get; set; }
        public string? Agency { get; set; }
        public string? Image { get; set; }
        public string? Wikipedia { get; set; }
        public string[]? Launches { get; set; }
        public string? Status { get; set; }
        public string? Id { get; set; }
    }
}

SpaceXUI/Models/ErrorViewModel.cs
namespace SpaceXUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SpaceXUI/Controllers/CrewController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SpaceXDAL.EntityModles;
using SpaceXSL.Service_Actions;
using SpaceXUI.Models;

namespace SpaceXUI.Controllers
{
    public class CrewController : Controller
    {
        public IActionResult CrewInfo()
        {
            string crewJson = Actions.GetJson(1);
            List<CrewVM>? crewInfo = JsonConvert.DeserializeObject<List<CrewVM>>(crewJson);
            return View(crewInfo.ToList());

        }
    }
}

SpaceXUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SpaceXUI.Models;
using System.Diagnostics;

namespace SpaceXUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpaceXUI/Views/Crew/CrewInfo.cshtml
@model IEnumerable<SpaceXUI.Models.CrewVM>

@{
    ViewData["Title"] = "CrewInfo";
}

@ViewBag{
    Title = "CrewInfo";
}

<h1>@ViewBag.Title</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Agency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wikipedia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Agency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wikipedia)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
        </tr>
}
    </tbody>
</table>

SpaceXUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SpaceXUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpaceX Information</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SpaceXUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SpaceXUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crew" asp-action="CrewInfo">Crew Info</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Sean A. McKinney 2023 - SpaceXUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>